### ISSUE TITLE
Упражнение 12 не работает

### ISSUE THREAD

**Issue by bonchEquipment** [ProgMiner/mledu#1]
При нажатии на кнопку "отправить" вылетает сообщение  "Ошибка данных" в левом нижнем углу 
Пробовал данные:
 [epsilon = 0.05, gamma = 0.9, random_seed = 10]
 [epsilon = 0.1, gamma = 0.8, random_seed = 9]

**Comment by ProgMiner** [comment]
Скорее всего опечатка при вводе значений. У меня отрабатывает как надо:

Для первого набора:
# Алгоритм Q-алгоритм
Количество побед: 9678
Номер игры, в которой агент впервые одержал пятую победу: 153
Маршрут: ![image](https://user-images.githubusercontent.com/6567920/171965101-71d112e1-894c-429f-a4ff-e74fb5a09f78.png)

# Алгоритм SARSA
Количество побед: 38474
Номер игры, в которой агент впервые одержал пятую победу: 118
Маршрут: ![image](https://user-images.githubusercontent.com/6567920/171965120-143c8087-b110-4933-8bb7-b55906742cfa.png)

Для второго набора данных:

# Алгоритм Q-алгоритм
Количество побед: 8267
Номер игры, в которой агент впервые одержал пятую победу: 367
Маршрут: ![image](https://user-images.githubusercontent.com/6567920/171965252-6b960e31-f6a4-466d-b68a-667e10213f91.png)
# Алгоритм SARSA
Количество побед: 32730
Номер игры, в которой агент впервые одержал пятую победу: 370
Маршрут: ![image](https://user-images.githubusercontent.com/6567920/171965291-b78f5024-62ae-4879-80e7-6dffac0d984b.png)
